# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-25 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sem',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
