# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-10 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_newsfeeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
