# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-11 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeeds',
            name='sub',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
