# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-16 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_newsfeeds_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dept',
            field=models.CharField(choices=[('6', '6'), ('4', '6')], max_length=30),
        ),
    ]
