# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-27 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_chat_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='classinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.classroom'),
            preserve_default=False,
        ),
    ]
