# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20190509_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='sub',
        ),
        migrations.AddField(
            model_name='assignment',
            name='sem',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
