# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_assignmentans'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='dept',
            field=models.CharField(choices=[('BCA', 'BCA'), ('BBA', 'BBA'), ('BCOM', 'BCOM')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sem',
            field=models.CharField(choices=[('6', 'Sixth'), ('4', 'Fourth'), ('2', 'Second')], max_length=10),
        ),
    ]
