# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20190509_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='Attachments',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='Paper',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='body',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='sub',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sem',
            field=models.CharField(choices=[('6', '6'), ('4', '4'), ('2', '2')], max_length=10),
        ),
    ]
