# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20190509_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
