# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_assignment_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='created',
        ),
    ]
