# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_remove_assignment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='sol',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
