# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_assignment_sol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='sol',
        ),
    ]
