# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_remove_assignment_sol'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
