# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0012_auto_20190509_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='created',
        ),
    ]
