# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0013_remove_assignment_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignmentans',
            name='user',
        ),
        migrations.DeleteModel(
            name='AssignmentAns',
        ),
    ]
