# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0014_auto_20190509_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(choices=[('BCA', 'BCA'), ('BBA', 'BBA'), ('BCOM', 'BCOM')], max_length=3)),
                ('sem', models.CharField(choices=[('6', '6'), ('4', '4'), ('2', '2')], max_length=10)),
                ('Paper', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('sub', models.CharField(max_length=400)),
                ('body', models.TextField(blank=True, max_length=5000, null=True)),
                ('Attachments', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sol', models.CharField(max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
