# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0015_assignment_assignmentans'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='sol',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
