# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0017_remove_assignment_sol'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
