# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0018_assignment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='From',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
