# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0019_assignment_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentans',
            old_name='sol',
            new_name='Solution',
        ),
        migrations.RenameField(
            model_name='assignmentans',
            old_name='title',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='assignmentans',
            name='Attachments',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='assignmentans',
            name='Paper',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentans',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentans',
            name='sub',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
