# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0020_auto_20190509_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentans',
            name='Solution',
            field=models.TextField(max_length=5000),
        ),
    ]
