# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-09 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0021_auto_20190509_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentans',
            old_name='Attachments',
            new_name='Attachment',
        ),
    ]
